openapi: 3.0.0
info:
  title: Pokemon API
  description: An API that will call AWS DynamoDB to get and store user data on a Pokémon
  version: 1.0.0
servers:
  - url: "http://localhost:5000"
tags:
  - name: Users
    description: Pokemon websites users
paths:
  /user:
    post:
      tags:
        - Users
      summary: Create User
      description: Create a new user profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                name:
                  type: string
                email:
                  type: string
                bio:
                  type: string
                password:
                  type: string
                profilePicture:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/validate/password:
    post:
      tags:
        - Users
      summary: Check password
      description: Compare the input password and the hashed password to see if they match
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                inputPassword:
                  type: string
                hashedPassword:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
